MyEshop/Areas/Admin/Controllers/Product_GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DataLayer;

namespace MyEshop.Areas.Admin.Controllers
{
    public class Product_GroupsController : Controller
    {
        private MyEshop_DBEntities db = new MyEshop_DBEntities();

        // GET: Admin/Product_Groups
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListGroups()
        {
            var product_Groups = db.Product_Groups.Where(g => g.ParentID == null);
            return PartialView(product_Groups.ToList());
        }

        // GET: Admin/Product_Groups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_Groups product_Groups = db.Product_Groups.Find(id);
            if (product_Groups == null)
            {
                return HttpNotFound();
            }
            return View(product_Groups);
        }

        // GET: Admin/Product_Groups/Create
        public ActionResult Create(int? id)
        {
            return PartialView(new Product_Groups()
            {
                ParentID = id
            });
        }

        // POST: Admin/Product_Groups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupID,GroupTitle,ParentID")] Product_Groups product_Groups)
        {
            if (ModelState.IsValid)
            {
                db.Product_Groups.Add(product_Groups);
                db.SaveChanges();
                return PartialView("ListGroups", db.Product_Groups.Where(g => g.ParentID == null));
            }

            ViewBag.ParentID = new SelectList(db.Product_Groups, "GroupID", "GroupTitle", product_Groups.ParentID);
            return View(product_Groups);
        }

        // GET: Admin/Product_Groups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_Groups product_Groups = db.Product_Groups.Find(id);
            if (product_Groups == null)
            {
                return HttpNotFound();
            }
            
            return PartialView(product_Groups);
        }

        // POST: Admin/Product_Groups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupID,GroupTitle,ParentID")] Product_Groups product_Groups)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product_Groups).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("ListGroups", db.Product_Groups.Where(g => g.ParentID == null));
            }
            ViewBag.ParentID = new SelectList(db.Product_Groups, "GroupID", "GroupTitle", product_Groups.ParentID);
            return View(product_Groups);
        }

        // GET: Admin/Product_Groups/Delete/5
        public void Delete(int id)
        {
            var group = db.Product_Groups.Find(id);
            if (group.Product_Groups1.Any())
            {
                foreach (var subGroup in db.Product_Groups.Where(g=>g.ParentID==id))
                {
                    //db.Entry(subGroup).State = EntityState.Deleted;
                    db.Product_Groups.Remove(subGroup);
                }
            }
            db.Product_Groups.Remove(group);
            db.SaveChanges();
        }

        // POST: Admin/Product_Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product_Groups product_Groups = db.Product_Groups.Find(id);
            db.Product_Groups.Remove(product_Groups);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyEshop/Areas/Admin/Views/Product_Groups/Create.cshtml
@model DataLayer.Product_Groups

@{
    ViewBag.Title = "Create";
}



@using (Ajax.BeginForm("Create","Product_Groups",FormMethod.Post,new AjaxOptions()
{
    OnSuccess = "success",
    UpdateTargetId = "listGroup"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.ParentID)
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.GroupTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupTitle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ثبت گروه" class="btn btn-success" />
            </div>
        </div>
    </div>
}

MyEshop/Areas/Admin/Views/Product_Groups/Delete.cshtml
@model DataLayer.Product_Groups

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product_Groups</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Groups2.GroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Groups2.GroupTitle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyEshop/Areas/Admin/Views/Product_Groups/Details.cshtml
@model DataLayer.Product_Groups

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product_Groups</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Product_Groups2.GroupTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product_Groups2.GroupTitle)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.GroupID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyEshop/Areas/Admin/Views/Product_Groups/Edit.cshtml
@model DataLayer.Product_Groups

@{
    ViewBag.Title = "Edit";
}



@using (Ajax.BeginForm("Edit","Product_Groups",FormMethod.Post,new AjaxOptions()
{
    OnSuccess = "success",
    UpdateTargetId = "listGroup"
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m=>m.ParentID)
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.GroupID)

        <div class="form-group">
            @Html.LabelFor(model => model.GroupTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GroupTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GroupTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ویرایش" class="btn btn-warning" />
            </div>
        </div>
    </div>
}

MyEshop/Areas/Admin/Views/Product_Groups/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a class="btn btn-success" onclick="Create()">افزودن سرگروه جدید</a>
</p>

<div id="listGroup">
    @Html.Action("ListGroups")
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body" id="myModalBody">
                ...
            </div>
        </div>
    </div>
</div>

<script>
    function Create(parentId) {
        $.get("/Admin/Product_Groups/Create/"+parentId,
            function(result) {
                $("#myModal").modal();
                $("#myModalLabel").html("افزودن گروه جدید");
                $("#myModalBody").html(result);
            });
    }

    function Edit(id) {
        $.get("/Admin/Product_Groups/Edit/" + id,
            function(result) {
                $("#myModal").modal('show');
                $("#myModalLabel").html("ویرایش گروه");
                $("#myModalBody").html(result);
            });
    }

    function Delete(id) {
        if (confirm("آیا از حذف مطمئن هستید ؟")) {
            $.get("/Admin/Product_Groups/Delete/" + id,
                function() {
                    $("#group_" + id).hide('slow');
                });
        }
    }

    function success() {
        $("#myModal").modal('hide');
    }
</script>

MyEshop/Areas/Admin/Views/Product_Groups/ListGroups.cshtml
@model IEnumerable<DataLayer.Product_Groups>

<table class="table table-bordered">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.GroupTitle)
        </th>
        <th>
            زیر گروه ها
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr id="group_@(item.GroupID)">
            <td>
                @Html.DisplayFor(modelItem => item.GroupTitle)
            </td>
            <td>
                @if (item.Product_Groups1.Any())
                {
                    <ul>
                        @foreach (var subGroup in item.Product_Groups1)
                        {
                            <li id="group_@(subGroup.GroupID)">
                                @subGroup.GroupTitle     <a class="text-warning" onclick="Edit(@subGroup.GroupID)">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                            <a class="text-danger" onclick="Delete(@subGroup.GroupID)">
                                <i class="glyphicon glyphicon-trash"></i>
                            </a>
                        </li>
                        }
                    </ul>
                }
            </td>
            <td>
                <a class="btn btn-primary btn-xs" onclick="Create(@item.GroupID)">
                    <i class="glyphicon glyphicon-plus"></i>
                </a>
                <a class="btn btn-warning btn-xs" onclick="Edit(@item.GroupID)">
                    <i class="glyphicon glyphicon-edit"></i>
                </a>
                <a class="btn btn-danger btn-xs" onclick="Delete(@item.GroupID)">
                    <i class="glyphicon glyphicon-trash"></i>
                </a>
            </td>
        </tr>
    }

</table>